title: Kirsten de Beurs # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  President's Associates Presidential Professor
  <br><br>
  I am currently also the Director for OU's online MS Geospatial Technologies. This program is entirely online. You can find more information <a href = "https://www.ou.edu/ags/geography/degree-programs/graduate-program/geography-m-s-online">here</a>
  <br><br>
  <a href="https://www.linkedin.com/in/kirsten-de-beurs-a78275102/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

